-- MySQL Script generated by MySQL Workbench
-- 06/15/16 21:17:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bankaccount
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bankaccount
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bankaccount` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bankaccount` ;

-- -----------------------------------------------------
-- Table `bankaccount`.`conta_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankaccount`.`conta_tipo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankaccount`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankaccount`.`conta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_tipo` INT UNSIGNED NOT NULL COMMENT '',
  `saldo` DOUBLE NULL COMMENT '',
  `limite` DOUBLE NULL COMMENT '',
  `montante_minimo` DOUBLE NULL COMMENT '',
  `deposito_minimo` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_conta_to_conta_tipo_id_idx` (`id_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_conta_to_conta_tipo_id`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `bankaccount`.`conta_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankaccount`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankaccount`.`cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(150) NULL COMMENT '',
  `sobrenome` VARCHAR(150) NULL COMMENT '',
  `rg` VARCHAR(15) NULL COMMENT '',
  `cpf` VARCHAR(18) NULL COMMENT '',
  `endereco` VARCHAR(255) NULL COMMENT '',
  `id_conta` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_cliente_to_conta_id_idx` (`id_conta` ASC)  COMMENT '',
  CONSTRAINT `fk_cliente_to_conta_id`
    FOREIGN KEY (`id_conta`)
    REFERENCES `bankaccount`.`conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bankaccount`.`conta_tipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `bankaccount`;
INSERT INTO `bankaccount`.`conta_tipo` (`id`, `nome`) VALUES (1, 'Conta Corrente');
INSERT INTO `bankaccount`.`conta_tipo` (`id`, `nome`) VALUES (2, 'Conta Investimento');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bankaccount`.`cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `bankaccount`;
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (1, 'Bruno Henrique', 'Woisa', '9.665.662-9', '080.272.809-07', 'Rua das Andorinhas, 1500', DEFAULT);
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (2, 'Guilherme', 'Budnieswski', '063.538.649-65', '012.840.354-00', 'Rua das Flores, 2503', DEFAULT);
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (3, 'Fabiano Sarzi', 'Sartori', '12.945.644-00', '321.963.147-00', 'Rua Javari, 350', DEFAULT);
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (4, 'Vera Lúcia Lerias da', 'Silva', '022.325.AS5-06', '753.951.852-25', 'Rua Lindóia, 94', DEFAULT);
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (5, 'Victor', 'Fernandez', '072.854.9AQ-07', '616.750.161-00', 'Rua União da Vitória, 98', DEFAULT);

COMMIT;

