-- MySQL Script generated by MySQL Workbench
-- 06/16/16 19:40:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bankaccount
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bankaccount
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bankaccount` DEFAULT CHARACTER SET utf8 ;
USE `bankaccount` ;

-- -----------------------------------------------------
-- Table `bankaccount`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankaccount`.`cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL,
  `sobrenome` VARCHAR(150) NULL,
  `rg` VARCHAR(15) NULL,
  `cpf` VARCHAR(18) NULL,
  `endereco` VARCHAR(255) NULL,
  `id_conta` INT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankaccount`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankaccount`.`conta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tipo` INT UNSIGNED NOT NULL,
  `saldo` DOUBLE NULL,
  `limite` DOUBLE NULL,
  `montante_minimo` DOUBLE NULL,
  `deposito_minimo` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankaccount`.`conta_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankaccount`.`conta_tipo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bankaccount`.`cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `bankaccount`;
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (1, 'Bruno Henrique', 'Woisa', '9.665.662-9', '080.272.809-07', 'Rua das Andorinhas, 1500', NULL);
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (2, 'Guilherme', 'Budnieswski', '063.538.649-65', '012.840.354-00', 'Rua das Flores, 2503', NULL);
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (3, 'Fabiano Sarzi', 'Sartori', '12.945.644-00', '321.963.147-00', 'Rua Javari, 350', NULL);
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (4, 'Vera Lúcia Lerias da', 'Silva', '022.325.AS5-06', '753.951.852-25', 'Rua Lindóia, 94', NULL);
INSERT INTO `bankaccount`.`cliente` (`id`, `nome`, `sobrenome`, `rg`, `cpf`, `endereco`, `id_conta`) VALUES (5, 'Victor', 'Fernandez', '072.854.9AQ-07', '616.750.161-00', 'Rua União da Vitória, 98', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bankaccount`.`conta_tipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `bankaccount`;
INSERT INTO `bankaccount`.`conta_tipo` (`id`, `nome`) VALUES (1, 'Conta Corrente');
INSERT INTO `bankaccount`.`conta_tipo` (`id`, `nome`) VALUES (2, 'Conta Investimento');

COMMIT;

